# Codemagic Configuration for PayTrack Simple Build
workflows:
  android-workflow:
    name: PayTrack Android APK
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Use Simple Configuration
        script: |
          cp pubspec_simple.yaml pubspec.yaml
          cp lib/main_simple.dart lib/main.dart
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
        ignore_failure: true
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/flutter-apk/*.apk
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - anilchowdary07@example.com  # Replace with your email
        notify:
          success: true
          failure: true
