name: paytrack_premium
description: "PayTrack Premium - Complete Payment Reminder & Spending Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  lottie: ^3.1.0
  intl: ^0.19.0
  animated_bottom_navigation_bar: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
